#!/usr/bin/env python
import argparse
import subprocess
import os, glob, shutil
parser = argparse.ArgumentParser()
parser.add_argument("packages",help="A list of all packages you want to install",nargs='+')
parser.add_argument("-d","--dir",help="The directory you want to install the packages to (the default is the current directory)",default=".")
args=parser.parse_args()

subprocess.run(["pip","install"]+args.packages+["-t",args.dir])

args.packages=[]
for file in glob.glob(os.path.join(args.dir,'*.dist-info')):
    args.packages.append(os.path.basename(file).split('-',1)[0])
    shutil.rmtree(file)
shutil.rmtree(os.path.join(args.dir,'bin'),ignore_errors=True)

for package in args.packages:
    subprocess.run(["mod-comment",os.path.join(args.dir,package)])
    if os.path.isdir(os.path.join(args.dir,package)):
        subprocess.run(["mod-convert",os.path.join(args.dir,package),os.path.join(args.dir,package+'.py')])
